// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::{attendees, events, tickets, venues};
use bigdecimal::BigDecimal;
use chrono::NaiveDateTime;
use diesel::{prelude::Queryable, Selectable};

#[derive(Queryable, Debug)]
pub struct Attendee {
    pub id: i32,
    pub name: String,
    pub email: String,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
    pub password_hash: Option<String>,
    pub salt: Option<String>,
    pub is_admin: Option<bool>,
}

#[derive(Queryable, Debug, Selectable)]
#[diesel(table_name = events)]
#[diesel(check_for_backend(diesel::pg::Pg))]
pub struct Event {
    pub id: i32,
    pub name: String,
    pub event_date: NaiveDateTime,
    pub location: Option<String>,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Ticket {
    pub id: i32,
    pub event_id: Option<i32>,
    pub attendee_id: Option<i32>,
    pub ticket_type: Option<String>,
    pub price: Option<BigDecimal>,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
}

#[derive(Queryable, Debug)]
pub struct Venue {
    pub id: i32,
    pub name: String,
    pub address: Option<String>,
    pub capacity: Option<i32>,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
}
